[tox]
envlist = pep8, py312


[testenv]
setenv = VIRTUAL_ENV={envdir}
         PYTHONWARNINGS=default::DeprecationWarning
commands =
    pytest {posargs}
deps =
    -c{env:TOX_CONSTRAINTS_FILE:https://releases.openstack.org/constraints/upper/2026.1}
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/test-requirements.txt

[testenv:pep8]
description = Run style checks.
skip_install = true
deps = pre-commit
commands = pre-commit run --all-files --show-diff-on-failure

[flake8]
show-source = True
select = H,O
# H404 Docstrings don't always start with a newline
# H405 Multiline docstrings are okay
ignore = H301,H403,H404,H405
import-order-style = pep8
application-import-names = nectar_metrics

[testenv:cover]
setenv =
    {[testenv]setenv}
commands =
    pytest --cov=nectar_metrics --cov-report=html:cover --cov-report=xml:cover/coverage.xml --cov-report=term {posargs}

[testenv:releasenotes]
deps = reno
commands = reno report
